export const SERVER = {
  FETCH_POST_REQUEST: "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE: "FETCH_POST_FAILURE",
  RECEIVE_POSTS: "RECEIVE_POSTS",
};

export const USER = {
  SELECT_SUBREDDIT: "SELECT_SUBREDDIT",
  INVALIDATE_SUBREDDIT: "INVALIDATE_SUBREDDIT",
};
// Reddit headlines
